config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "questionnaire#index"
  post 'questionnaire/submit', to: 'questionnaire#submit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/questionnaire.rb
require "pstore" # https://github.com/ruby/pstore
class Questionnaire < ApplicationRecord

  def self.do_report
    # calculate total rating and total runs
    store = PStore.new(STORE_NAME)
    total_rating = 0
    total_runs = 0
    store.transaction(true) do
      store.roots.each do |timestamp|
        responses = store[timestamp]
        if responses
          rating = 100 * responses.values.count("Yes") / QUESTIONS.count
          total_rating += rating
          total_runs += 1
        end
      end

      # calculate average rating over all runs based on yes responses given by each user, only if total runs are greater than 0.
      @average_rating = (total_rating/total_runs) if total_runs > 0
      puts "Avarage Rating over all run : #{@average_rating}"
    end
    
    @average_rating
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questionnaire_controller.rb
class QuestionnaireController < ApplicationController
  def index
    @questions = QUESTIONS
    @score = params[:score] if params.present?
    flash[:alert] = params[:notice]
    @average_rating = Questionnaire.do_report
  end

  def submit
    responses = params[:responses]
    if responses
      store_responses(responses)
      @score = 100 * responses.values.count('Yes') / QUESTIONS.count
      redirect_to root_path(score: @score, notice: "Survey submitted successfully!")
    else
      redirect_to root_path(score: @score, notice: "Please select some value to submit response")
    end
  end

  private

  def store_responses(responses)
    store = PStore.new(STORE_NAME)
    store.transaction do
      store[Time.now] = responses
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurveyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questionnaire/_form.html.erb
<%= form_with(model: questionnaire) do |form| %>
  <% if questionnaire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(questionnaire.errors.count, "error") %> prohibited this questionnaire from being saved:</h2>

      <ul>
        <% questionnaire.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questionnaire/edit.html.erb
<h1>Editing Questionnaire</h1>

<%= render 'form', questionnaire: @questionnaire %>

<%= link_to 'Show', @questionnaire %> |
<%= link_to 'Back', questionnaires_path %>

app/views/questionnaire/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Survey</title>
</head>

<body>
  <h1> Survey </h1>

    <% if flash[:alert].present? %>
      <div class="alert">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= form_tag(questionnaire_submit_path) do %>
      <% @questions.each do |key, question| %>
        <div class="question">
          <p><%= question %></p>
          <%= radio_button_tag "responses[#{key}]", 'Yes' %> Yes
          <%= radio_button_tag "responses[#{key}]", 'No' %> No
        </div>
      <% end %>
      <%= submit_tag "Submit Survey" %>
    <% end %>

  <h3> Score <%= @score %></h3>
  <h3> Average Rating: <%= @average_rating %></h3>

</body>
</html>

app/views/questionnaire/new.html.erb
<h1>New Questionnaire</h1>

<%= render 'form', questionnaire: @questionnaire %>

<%= link_to 'Back', questionnaires_path %>

app/views/questionnaire/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_questionnaire_path(@questionnaire) %> |
<%= link_to 'Back', questionnaires_path %>